const countryEmojis: { [key: string]: string } = {
  "United States": "🇺🇸",
  Canada: "🇨🇦",
  Mexico: "🇲🇽",
  "United Kingdom": "🇬🇧",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Italy: "🇮🇹",
  Spain: "🇪🇸",
  Australia: "🇦🇺",
  India: "🇮🇳",
  China: "🇨🇳",
  Japan: "🇯🇵",
  Brazil: "🇧🇷",
  "South Africa": "🇿🇦",
  "Costa Rica": "🇨🇷",
  Argentina: "🇦🇷",
  Chile: "🇨🇱",
  Colombia: "🇨🇴",
  Peru: "🇵🇪",
  "New Zealand": "🇳🇿",
  Russia: "🇷🇺",
  "South Korea": "🇰🇷",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Finland: "🇫🇮",
  Denmark: "🇩🇰",
  Netherlands: "🇳🇱",
  Belgium: "🇧🇪",
  Switzerland: "🇨🇭",
  Austria: "🇦🇹",
  Greece: "🇬🇷",
  Portugal: "🇵🇹",
  Turkey: "🇹🇷",
  Israel: "🇮🇱",
  Egypt: "🇪🇬",
  "Saudi Arabia": "🇸🇦",
  "United Arab Emirates": "🇦🇪",
  Singapore: "🇸🇬",
  Malaysia: "🇲🇾",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  Philippines: "🇵🇭",
  Indonesia: "🇮🇩",
  Bangladesh: "🇧🇩",
  Pakistan: "🇵🇰",
  Iraq: "🇮🇶",
  Iran: "🇮🇷",
  Afghanistan: "🇦🇫",
  Kazakhstan: "🇰🇿",
  Ukraine: "🇺🇦",
  Poland: "🇵🇱",
  "Czech Republic": "🇨🇿",
  Hungary: "🇭🇺",
  Slovakia: "🇸🇰",
  Romania: "🇷🇴",
  Bulgaria: "🇧🇬",
  Serbia: "🇷🇸",
  Croatia: "🇭🇷",
  Slovenia: "🇸🇮",
  Lithuania: "🇱🇹",
  Latvia: "🇱🇻",
  Estonia: "🇪🇪",
  Moldova: "🇲🇩",
  Georgia: "🇬🇪",
  Armenia: "🇦🇲",
  Azerbaijan: "🇦🇿",
  Jamaica: "🇯🇲",
  "Dominican Republic": "🇩🇴",
  Haiti: "🇭🇹",
  Cuba: "🇨🇺",
  Barbados: "🇧🇧",
  "Trinidad and Tobago": "🇹🇹",
  Bahamas: "🇧🇸",
  "Saint Lucia": "🇱🇨",
  "Saint Vincent and the Grenadines": "🇻🇨",
  Grenada: "🇬🇩",
  "Antigua and Barbuda": "🇦🇬",
  Dominica: "🇩🇲",
  Belize: "🇧🇿",
  Guatemala: "🇬🇹",
  "El Salvador": "🇸🇻",
  Nicaragua: "🇳🇮",
  Panama: "🇵🇦",
  // Add more countries and their emojis as needed
};

export const getCountryEmoji = (country: string): string => {
  return countryEmojis[country] || ""; // Return empty string if country not found
};
